name: "Build Physics Notes"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Physics Notes Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Physics Notes"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: pipenv
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: "Install Python Dependencies"
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python3
          pipenv install
      - name: "Install mkdocs-material"
        run: |
          pip install mkdocs-material
      - name: "Build Physics Notes"
        run: |
          pipenv run mkdocs build
      - name: "Deploy Physics Notes"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          cname: phy.shuzhouliu.bio
          keep_files: false
          user_name: shuzhouliu
          user_email: shuzhou.liu@hotmail.com